Repository TDUSenjuAstronomyResearchClub/CanSat02, pull requests merged in 2023-07, with the labels that each got.

#61 土壌水分量取得モジュールを修正
  cansatapi/soil_moisture.py
Labels: バグ, 改善

#62 サーボを修正
  cansatapi/servo.py
Labels: バグ

#63 土壌水分量センサの動作確認モジュールの修正
  operation_check/oc_soil_moisture.py
Labels: 改善, 動作確認

#81 Excelに対応したログフォーマットに変更
  cansatapi/util/logging.py
Labels: 改善

#83 基盤v2.2対応のピン番号に変更
  cansatapi/distance.py
  operation_check/oc_servo.py
Labels: 改善
